config/routes.rb
ControllerTest::Application.routes.draw do
  root "users#start"
  #namespace :admin do
  #  resources :users do
  #    resources :tweets
  #  end
  #end
  
  resources :users,except: [:index] do
   collection do
    get 'sign_up' => 'users#sign_up'
    post 'enter' => 'users#enter'
    get 'log_out' => 'users#log_out',as: 'log_out'
   end

  end
   resources :twitts,only:[:create,:destroy] do
     post 'retwitt',on: :member
   end

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/dependence.rb
class Dependence < ActiveRecord::Base
  belongs_to :user
  belongs_to :twitt
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :subscription,class_name: User
  belongs_to :follower,class_name: User
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/twitt.rb
class Twitt < ActiveRecord::Base
  belongs_to :owner,class_name: User 

  has_many :users,through: :dependences
  has_many :dependences
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,presence: true

  has_many :twitts,through: :dependences
  has_many :dependences

  
  has_many :subscriptions,through: :relations
  has_many :followers,through: :relations
  has_many :relations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
    def current_user
      @current_user ||= cur_id && User.find_by(id: cur_id)
    end
    
    def cur_id
      session[:current_user_id]
    end

end

app/controllers/twitts_controller.rb
class TwittsController < ApplicationController

  def create
    @twitt = Twitt.new(twitt_params)
    if @twitt.save
      current_user.twitts << @twitt
      redirect_to current_user
    else
      render 'show'
    end
  end

  def destroy
    Twitt.find_by(id: params[:id]).destroy
    redirect_to current_user
  end

  def retwitt
    current_user.twitts << Twitt.find_by(id: params[:id]) 
    redirect_to current_user
  end

  private
    def twitt_params
      hash = params.require(:twitt).permit(:text)
      hash[:owner_id] = current_user.id
      hash
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in,only: [:edit,:update,:destroy]
  before_action :presence_id,only: [:show]

  def start
    if current_user
      redirect_to current_user
    else
      redirect_to new_user_path
    end
  end

  def show
    @twitt = Twitt.new
    @user = User.find_by(id:  params[:id] || cur_id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_in_params)
    if @user.save
      set_id @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def sign_up
    @user = User.new
  end

  def enter
    if @user = User.find_by(sign_up_params)
      set_id @user.id    
      redirect_to @user
    else
      render 'sign_up'
    end
  end

  def edit
    @user = current_user 
  end

  def update
    @user = current_user
    if @user.update_attributes(sign_in_params)
      redirect_to @user 
    else
      render 'edit'
    end
  end

  def log_out
    reset_id
    binding.pry
    redirect_to sign_up_users_path
  end

  def destroy
    @user = current_user
    @user.destroy
    reset_id
    redirect_to sign_in_users_path
  end

  private

   def presence_id
      unless  cur_id || params[:id]
        redirect_to sign_up_users_path
      end
   end

   def set_id(id)
     session[:current_user_id] = id
   end
  
   def reset_id
     session[:current_user_id] = nil
   end
   
   def logged_in
     if cur_id != params[:id].to_i
        redirect_to :root
     end
   end
   
   def sign_up_params
     params.require(:user).permit(:login,:password)
   end

   def sign_in_params
     params.require(:user).permit(:login,:password,:email,:name,:surname,:photo,:info)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitts_helper.rb
module TwittsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ControllerTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>

  <span class="log_out">
    <%=link_to 'log_out',log_out_users_path%>
    <br>
    <%=link_to 'sign_up',sign_up_users_path%>
    <br>
    <%=link_to 'sing_in',new_user_path%>
  </span>  

  <%= yield %>

</body>
</html>

app/views/twitts/_twitt.html.haml
= "_"*30
%br
= twitt.text
%br

app/views/twitts/_twitt_form.html.haml
=form_for @twitt do |f|
  =f.text_area :text
  %br
  =f.submit

app/views/users/_sign_in_form.html.haml
=form_for @user do |f|
  =f.label :login
  %br
  =f.text_field :login
  %br
  =f.label :password
  %br
  =f.password_field :password
  %br
  =f.label :name
  %br
  =f.text_field :name
  %br
  =f.label :surname
  %br
  =f.text_field :surname
  %br
  =f.label :email
  %br
  =f.text_field :email
  %br
  =f.label :info
  %br
  =f.text_area :info
  %br
  =f.submit
  

app/views/users/_sing_up_form.html.haml
=form_for @user,url: {action: :enter} do |f|
  =f.label :login
  %br
  =f.text_field :login
  %br
  =f.label :password
  %br
  =f.password_field :password
  %br
  =f.submit
  

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit.html.haml
=render 'sing_in_form'

app/views/users/new.html.haml
=render 'sign_in_form'

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/show.html.haml
=@user.name
%br
=@user.surname
%br
=render('twitts/twitt_form') if params[:id] == session[:current_user_id].to_s
%br
=render @user.twitts

app/views/users/sign_up.html.haml
=render 'sing_up_form'

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>